// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DYfHRiQFx8tdRyn_WjEYHfEVail7aU0',
    appId: '1:714869909868:web:3d978e9e13330aa9482b49',
    messagingSenderId: '714869909868',
    projectId: 'e-smarthome-62391',
    authDomain: 'e-smarthome-62391.firebaseapp.com',
    databaseURL: 'https://e-smarthome-62391-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-smarthome-62391.firebasestorage.app',
    measurementId: 'G-PNS693JK1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASY4d0oIPLu-SeRAx7zA1XROHrPSu6dS8',
    appId: '1:714869909868:android:9daa6a18584a6d85482b49',
    messagingSenderId: '714869909868',
    projectId: 'e-smarthome-62391',
    databaseURL: 'https://e-smarthome-62391-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-smarthome-62391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF5D4ibgmBj---UQg69uIhvM8af8JBu-8',
    appId: '1:714869909868:ios:995cde5accf3ad2f482b49',
    messagingSenderId: '714869909868',
    projectId: 'e-smarthome-62391',
    databaseURL: 'https://e-smarthome-62391-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-smarthome-62391.firebasestorage.app',
    iosBundleId: 'com.example.esh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF5D4ibgmBj---UQg69uIhvM8af8JBu-8',
    appId: '1:714869909868:ios:995cde5accf3ad2f482b49',
    messagingSenderId: '714869909868',
    projectId: 'e-smarthome-62391',
    databaseURL: 'https://e-smarthome-62391-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-smarthome-62391.firebasestorage.app',
    iosBundleId: 'com.example.esh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DYfHRiQFx8tdRyn_WjEYHfEVail7aU0',
    appId: '1:714869909868:web:5aeb0049e29c9cd0482b49',
    messagingSenderId: '714869909868',
    projectId: 'e-smarthome-62391',
    authDomain: 'e-smarthome-62391.firebaseapp.com',
    databaseURL: 'https://e-smarthome-62391-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-smarthome-62391.firebasestorage.app',
    measurementId: 'G-VNE1EGXN8D',
  );
}
