[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM19	
monitor_port = COM19
monitor_speed = 115200
board_build.partitions = default.csv
build_flags = 
    -DBOARD_PINS_ESP32_S3
    -DCORE_DEBUG_LEVEL=0
    -I include
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
